script: bin/bacon -Ilib --automatic --quiet
rvm:
- 1.8.7
- 1.9.2
- 1.9.3
- rbx-18mode
- rbx-19mode
- jruby-18mode
- jruby-19mode
notifications:
  recipients:
  - gabriel.horner@gmail.com
matrix:
  # until issues are fixed
  allow_failures:
  - rvm: rbx-18mode
  - rvm: rbx-19mode
  - rvm: jruby-18mode
  - rvm: jruby-19mode
